plugins:
  - jekyll-feed
  - jekyll-sitemap

# SEO Stuff
author: Kai Andresen
description: En personlig blog
lang: no
locale: no_NB
url: "https://pale.rocks"
baseurl: ""

# RSS feeds
feed:
  posts_limit: 20
