plugins:
  - jekyll-feed
  - jekyll-sitemap

# SEO Stuff
author: Kai Andresen
description: litt om hva jeg får med meg, og hva jeg får ut av det
lang: no
url: "https://kaisunivers.org"
name: kaisunivers.org

# RSS feeds
feed:
  posts_limit: 20
